# Generated by Django 3.2.2 on 2021-05-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0002_auto_20210507_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restid', models.EmailField(max_length=254)),
                ('address_rest', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custid', models.EmailField(max_length=254)),
                ('address_user', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('review', models.CharField(max_length=1000, null=True)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodspark.customer')),
                ('restid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodspark.restaurant')),
            ],
        ),
    ]
